source: .
destination: ./_site
includes: ./_includes

markdown: rdiscount
highlighter: pygments
permalink: /:title.html

base_url: http://austinmcshan.com
exclude: ['config.rb', 'README.md', 'site.scss', 'tasks']

sass:
  sass_dir: _sass
  style:  :compressed