#!/usr/bin/env ruby

ROOT_DIR = File.join(File.dirname(__FILE__), '/..')

title = ARGV[0]

unless title
    puts %{Usage #{$0} "The post title"}
    exit(-1)
end 

datetime = (Time.now + 30*60).strftime('%Y-%m-%d')
slug = title.downcase.strip.gsub(' ', '-').gsub(/[^\w-]/, '')
path = "#{ROOT_DIR}/_posts/#{datetime}-#{slug}.md"

header = <<-END
---
layout: post
title: #{title}
slug: #{slug}
author: 
    name: Austin McShan
---

END

File.open(path, 'w'){ |f| f << header }
system('subl', '-a', path)